# Generated by Django 4.1.3 on 2022-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('deleted', models.BooleanField()),
                ('type', models.CharField(choices=[('JB', 'Job'), ('ST', 'Story'), ('CO', 'Comment'), ('PL', 'Poll'), ('PT', 'Pollopt')], default='ST', max_length=5)),
                ('by', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('dead', models.BooleanField()),
                ('kids', models.CharField(max_length=1000000)),
                ('descendants', models.IntegerField()),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
