# Generated by Django 4.1.3 on 2022-12-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaseStudy2', '0002_alter_news_options_alter_news_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='news',
            name='kids',
        ),
    ]
