# Generated by Django 4.1.3 on 2022-12-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseStudy2', '0003_remove_news_deleted_remove_news_kids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='dead',
        ),
        migrations.AddField(
            model_name='news',
            name='kids',
            field=models.CharField(default=[], max_length=1000000),
            preserve_default=False,
        ),
    ]
