# Generated by Django 4.1.3 on 2022-12-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaseStudy2', '0006_remove_news_kids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
    ]
